server:
  port: 8089

spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.231:3306/yicartrip_nuwa_cbs
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 初始化大小，最小，最大
#    initialSize: 5
#    minIdle: 5
#    maxActive: 50
#    # 配置获取连接等待超时的时间
#    maxWait: 670000
#    poolPreparedStatements: true
#    max-evictable-idle-time-millis: 8888888
#    timeBetweenEvictionRunsMillis: 60000
#    kill-when-socket-read-timeout: true
#    time-between-log-stats-millis: 66666
  profiles:
    include: redis,datasource




  redis:
    sentinel:
      master: r2
      nodes:
       - 192.168.1.231:56379
       - 192.168.1.232:56379
       - 192.168.1.235:56379
#    database: 0
#    timeout: 60000
#    jedis:
#      pool:
#        max-active: 300
#        min-idle: 20
#        max-idle: 100
#        max-wait: -1
#        time-between-eviction-runs: 600
#    password:

mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mapper/*/*.xml
  # pojo类所在包路径

threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 300




